### ISSUE TITLE
bundle is sourced before neobundle#end when it is depends on by another bundle

### ISSUE THREAD

**Issue by paulhybryant** [Shougo/neobundle.vim#491] opened 2016-01-22 06:46 UTC
minimal vimrc to reproduce:

set nocompatible
filetype off
set runtimepath+=$HOME/.vim/bundle/neobundle.vim/
call neobundle#begin('$HOME/.vim/bundle')
NeoBundleFetch 'Shougo/neobundle.vim'
NeoBundle 'google/vim-maktaba'
NeoBundle 'google/vim-glaive', { 'depends' : ['vim-maktaba'] }
echom neobundle#is_sourced('vim-maktaba')
call neobundle#end()
filetype plugin indent on

**Comment by Shougo** [comment] 2016-01-22 20:46
It is intended behavior.
Closing.

**Closed by Shougo** 2016-01-22 20:46 UTC

**Comment by paulhybryant** [comment] 2016-01-24 01:17
In the past no bundle will be sourced before neobundle#end(), is this not true anymore?

**Comment by paulhybryant** [comment] 2016-01-24 06:48
Also, the help document for NeoBundleDisable is the following:
NeoBundleDisable {name}...                     :NeoBundleDisable
                     Disables bundles specified by {name}.  If a bundle is
                     disabled, its path will be removed from 'runtimepath'.
                     Note: This command must be executed before neobundle loads
                     the plugins(after neobundle#end()).

But because the bundle can be sourced before neobundle#end(), NeoBundleDisable will complain that the bundle cannot be disabled, even if it is before neobundle#end().

**Comment by Shougo** [comment] 2016-01-24 23:18
> In the past no bundle will be sourced before neobundle#end(), is this not true anymore?

Yes.

> But because the bundle can be sourced before neobundle#end(), NeoBundleDisable will complain that the bundle cannot be disabled, even if it is before neobundle#end().

The plugin cannot be disabled.  Because, it is depended on other plugins.

**Comment by paulhybryant** [comment] 2016-01-25 01:36
Sure, I agreed that a plug cannot be disabled if it is depended by other plugins.
But I think a vimrc like the following should be valid:

set nocompatible
filetype off
set runtimepath+=$HOME/.vim/bundle/neobundle.vim/
call neobundle#begin('$HOME/.vim/bundle')
NeoBundleFetch 'Shougo/neobundle.vim'
NeoBundle 'google/vim-maktaba'
NeoBundle 'google/vim-glaive', { 'depends' : ['vim-maktaba'] }
NeoBundleDisable vim-glaive
NeoBundleDisable vim-maktaba
call neobundle#end()
filetype plugin indent on

However because vim-maktaba is sourced before neobundle#end(), the above NeoBundleDisable for vim-maktaba will be invalid.

**Comment by Shougo** [comment] 2016-01-25 21:19
Unfortunately, I cannot fix it.
neobundle's dependency feature is too complex.
In dein.vim, the dependency feature is improved.

**Comment by paulhybryant** [comment] 2016-01-26 01:10
ok, thanks for your time.
