### ISSUE TITLE
neobundle crash vim on update bundles

### ISSUE THREAD

**Issue by zdm** [Shougo/neobundle.vim#525] opened 2017-07-10 15:40 UTC
Hi.
When I tries to update bundles - latest vim v8.0.704 dies with segmentation fault on both systems: windows and linux.
Maybe the problem in vimproc, I don't know.

**Comment by Shougo** [comment] 2017-07-11 01:19
Vim 8.0.702 is broken.

https://groups.google.com/forum/#!topic/vim_dev/l5JhLQB_5xA/discussion

**Comment by zdm** [comment] 2017-07-21 22:41
So, it is already vim patch 740, vim is not crashing anymore, but neobundle stucking and doesn't reporting progress.

**Comment by Shougo** [comment] 2017-07-22 02:38
Really?
I will test it.
Please create the minimal vimrc and the reproduce ways.

**Comment by Shougo** [comment] 2017-07-22 02:39
Ah, please update vimproc to the latest version.
It is already updated.

**Comment by Shougo** [comment] 2017-07-22 02:40
Note:  I will close it if you not upload the minimal vimrc and the reproduce ways.

**Comment by zdm** [comment] 2017-07-22 05:54
Hi,
I already updated vimproc.
Here is my vimrc settings, related to the neobundle:

```
" init NeoBundle {{{
let g:user_profile_dir = substitute($HOME . "/.vim", '\\', '/', 'g')
let g:bundle_path = g:user_profile_dir . "/bundle"
let g:bundle_local_path = g:user_profile_dir . "/bundle-local"
exec "set rtp+=" . g:bundle_path . "/neobundle.vim"

call neobundle#begin(expand(g:bundle_path))

NeoBundleFetch "Shougo/neobundle.vim"

exec "NeoBundleLocal " . g:bundle_local_path
" }}}

NeoBundle 'Shougo/vimproc', " {{{
\{
\    'build': {
\        'windows': 'mingw32-make.exe -f make_mingw64.mak CC=gcc',
\        'cygwin': 'make -f make_cygwin.mak',
\        'mac': 'make -f make_mac.mak',
\        'unix': 'make -f make_unix.mak'
\    }
\}
" }}}
```

**Comment by Shougo** [comment] 2017-07-23 13:25
OK.  I will test it.  But ...

> exec "NeoBundleLocal " . g:bundle_local_path

Why it is needed for the minimal vimrc?

> NeoBundle 'Shougo/vimproc', " {{{

It should be `Shougo/vimproc.vim`.

**Comment by Shougo** [comment] 2017-07-23 13:26
> So, it is already vim patch 740, vim is not crashing anymore, but neobundle stucking and doesn't reporting progress.

It can be reproduce-able in Linux environment?

**Comment by Shougo** [comment] 2017-07-23 13:27
And please check vimproc works.
For example, to test vimshell and `vimproc#system()`.

**Comment by zdm** [comment] 2017-07-23 16:36
1. yes, it can be re-producible on Linux, this issue is present on both systems, windows and linux;
2. everything works on vim 8.0.0701 and earlier;
3. exec "NeoBundleLocal " . g:bundle_local_path - is not necessary, I just copied part of my vimrc;
4. I tried :VimProcRead ls - it works;

**Comment by Shougo** [comment] 2017-07-24 00:07
@zdm Please upload the reproduce ways with clean state from clone neobundle.
This is needed.

**Comment by Shougo** [comment] 2017-07-24 00:09
I don't remove `reproduce ways` flag until it.

**Comment by Shougo** [comment] 2017-07-24 01:56
Please read the neobundle documentation.

```vim
	NeoBundle 'Shougo/vimproc.vim', {
	      \   'build' : {
	      \     'windows' : 'tools\\update-dll-mingw',
	      \     'cygwin' : 'make -f make_cygwin.mak',
	      \     'mac' : 'make -f make_mac.mak',
	      \     'linux' : 'make',
	      \     'unix' : 'gmake',
	      \   }
	      \ }
```

I cannot reproduce the problem with it in Linux Ubuntu 16.04.

```vim
set rtp+=~/src/neobundle.vim/

call neobundle#begin(expand('~/.cache/neobundle'))

NeoBundle 'Shougo/vimproc.vim', " {{{
\{
\    'build': 'make'
\}
" }}}

call neobundle#end()
```

**Closed by Shougo** 2017-07-24 01:56 UTC
Labels: cannot reproduce, reproduce ways
